// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_suiGgTECyWKC7MB5-SsKjDXJvV2Y5gI',
    appId: '1:665973372347:web:48b6a0b39f91ecf0c3009e',
    messagingSenderId: '665973372347',
    projectId: 'random-quote-generator-80569',
    authDomain: 'random-quote-generator-80569.firebaseapp.com',
    storageBucket: 'random-quote-generator-80569.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLpB1o0Yem5Nl0RmafjuhWF2P02ZAE-5Q',
    appId: '1:665973372347:android:4bff7b2b33a98fb4c3009e',
    messagingSenderId: '665973372347',
    projectId: 'random-quote-generator-80569',
    storageBucket: 'random-quote-generator-80569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRPKr9diTVtzHc2MiV0l16eTJyKmIItkU',
    appId: '1:665973372347:ios:14b00df1371f7872c3009e',
    messagingSenderId: '665973372347',
    projectId: 'random-quote-generator-80569',
    storageBucket: 'random-quote-generator-80569.firebasestorage.app',
    iosBundleId: 'com.example.randomQuoteGenrator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRPKr9diTVtzHc2MiV0l16eTJyKmIItkU',
    appId: '1:665973372347:ios:14b00df1371f7872c3009e',
    messagingSenderId: '665973372347',
    projectId: 'random-quote-generator-80569',
    storageBucket: 'random-quote-generator-80569.firebasestorage.app',
    iosBundleId: 'com.example.randomQuoteGenrator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_suiGgTECyWKC7MB5-SsKjDXJvV2Y5gI',
    appId: '1:665973372347:web:f8afc021faa06b56c3009e',
    messagingSenderId: '665973372347',
    projectId: 'random-quote-generator-80569',
    authDomain: 'random-quote-generator-80569.firebaseapp.com',
    storageBucket: 'random-quote-generator-80569.firebasestorage.app',
  );
}
